version: '3.8'
services:
  postgres:
    image: postgres:latest
    container_name: postgresql
    volumes:
      - postgres_data:/var/lib/postgresql/data
    expose:
      - 5432
    ports:
      - 5432:5432
    environment:
      SPRING_PROFILES_ACTIVE: ${SPRING_PROFILES_ACTIVE}
      POSTGRES_USER: ${POSTGRES_DB_USERNAME}
      POSTGRES_PASSWORD: ${POSTGRES_DB_PASSWORD}
      POSTGRES_DB: notBookingDB
    restart: on-failure
    networks:
      - not-booking
  
  mongodb:
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - mongodb_data:/data/db
    networks:
      - not-booking

  reservation-ms:
    build:
      context: ./../reservation-ms
      dockerfile: Dockerfile
    ports:
      - 8081:8081
    depends_on:
      - mongodb
    environment:
      - MONGODB_HOST=mongodb
    networks:
      - not-booking
  user-ms:
    build:
      context: ./../user-ms
      dockerfile: Dockerfile
    ports:
      - 8082:8082
    restart: unless-stopped
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: ${SPRING_DATASOURCE_URL}
      SPRING_DATASOURCE_USERNAME: ${POSTGRES_DB_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${POSTGRES_DB_PASSWORD}
    networks:
      - not-booking
  notification-ms:
    build:
      context: ./../notification-ms
      dockerfile: Dockerfile
    ports:
      - 8083:8083
    restart: unless-stopped
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: ${SPRING_DATASOURCE_URL}
      SPRING_DATASOURCE_USERNAME: ${POSTGRES_DB_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${POSTGRES_DB_PASSWORD}
    networks:
      - not-booking
  overview-ms:
    build:
      context: ./../overview-ms
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    depends_on:
      - mongodb
    environment:
      - MONGODB_HOST=mongodb
    networks:
      - not-booking
  frontend:
    build:
      context: ./
      dockerfile: Dockerfile  
    ports:
      - 3000:3000
    networks:
      - not-booking

volumes:
  postgres_data:
  mongodb_data:

networks:
  not-booking: